# Generated by Django 3.0.2 on 2020-01-12 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=64)),
                ('year', models.IntegerField(default=2020, validators=[django.core.validators.MaxValueValidator(2020), django.core.validators.MinValueValidator(1930)])),
                ('manufacturer', models.CharField(max_length=64)),
            ],
        ),
    ]
