# Generated by Django 3.0.2 on 2020-01-12 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudcar', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cars',
            new_name='Car',
        ),
    ]
