# Generated by Django 3.0.2 on 2020-01-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudcar', '0002_auto_20200112_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(blank=True),
        ),
    ]
