# Generated by Django 3.0.2 on 2020-01-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudcar', '0003_auto_20200112_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
